version: '3.9'

services:
  nodejs:
    build:
      context: .
      dockerfile: ./compose/local/nodejs/Dockerfile
    image: nodejs_prod
    expose:
      - 3000
    volumes:
      - .:/app
  
  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: nginx_node
    depends_on:
      - nodejs
    ports:
      - 3000:3000
      - 80:80
      - 443:443